INSERT INTO states (id, name, slug, update_frequency) VALUES
('ap', 'Andhra Pradesh', 'andhra-pradesh', 'biannual'),
('ar', 'Arunachal Pradesh', 'arunachal-pradesh', 'biannual'),
('as', 'Assam', 'assam', 'biannual'),
('br', 'Bihar', 'bihar', 'biannual'),
('cg', 'Chhattisgarh', 'chhattisgarh', 'biannual'),
('ga', 'Goa', 'goa', 'annual'),
('gj', 'Gujarat', 'gujarat', 'biannual'),
('hp', 'Himachal Pradesh', 'himachal-pradesh', 'annual'),
('jh', 'Jharkhand', 'jharkhand', 'biannual'),
('kl', 'Kerala', 'kerala', 'biannual'),
('mp', 'Madhya Pradesh', 'madhya-pradesh', 'biannual'),
('mh', 'Maharashtra', 'maharashtra', 'biannual'),
('mn', 'Manipur', 'manipur', 'annual'),
('ml', 'Meghalaya', 'meghalaya', 'annual'),
('mz', 'Mizoram', 'mizoram', 'annual'),
('nl', 'Nagaland', 'nagaland', 'annual'),
('or', 'Odisha', 'odisha', 'biannual'),
('pb', 'Punjab', 'punjab', 'biannual'),
('rj', 'Rajasthan', 'rajasthan', 'biannual'),
('sk', 'Sikkim', 'sikkim', 'annual'),
('tn', 'Tamil Nadu', 'tamil-nadu', 'annual'),
('tg', 'Telangana', 'telangana', 'biannual'),
('tr', 'Tripura', 'tripura', 'biannual'),
('ut', 'Uttarakhand', 'uttarakhand', 'annual'),
('wb', 'West Bengal', 'west-bengal', 'biannual'),
('an', 'Andaman and Nicobar Islands', 'andaman-and-nicobar', 'annual'),
('ch', 'Chandigarh', 'chandigarh', 'biannual'),
('dn', 'Dadra and Nagar Haveli', 'dadra-nagar-haveli', 'biannual'),
('jk', 'Jammu and Kashmir', 'jammu-and-kashmir', 'annual'),
('la', 'Ladakh', 'ladakh', 'annual'),
('ld', 'Lakshadweep', 'lakshadweep', 'annual'),
('py', 'Puducherry', 'puducherry', 'annual');
